image: mkldevops/php:8.0

cache:
  paths:
    - vendor

stages:
  - CodingStandards
  - UniTests

cs-fixer:
  stage: CodingStandards
  script:
    - make cs-dry
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
    - make stan
  allow_failure: false

phpunit:
  stage: UniTests
  script:
    - make test-all
  allow_failure: false